import type { Checkpoint, LatLng, RouteResult } from './types';
import { geoDistance } from './math';
import { optimizeOpen, fallbackOrder } from './optimizer';
export const CONFIG={valhalla:'https://valhalla1.openstreetmap.de',osrm:'https://routing.openstreetmap.de/routed-foot'};
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const basePoint=(id:string,geo:LatLng):Checkpoint=>({id,number:'',geo,kind:'base'});
async function request(url:string,init:RequestInit={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),8000);try{const r=await fetch(url,{...init,signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json();}finally{clearTimeout(t);}}
async function valhalla(all:Checkpoint[]):Promise<RouteResult>{const data=await request(`${CONFIG.valhalla}/optimized_route`,{method:'POST',headers:{'content-type':'application/json','X-Client-Id':'harpagan-route-planner'},body:JSON.stringify({locations:all.map(p=>({lat:p.geo.lat,lon:p.geo.lon})),costing:'pedestrian',units:'kilometers',shape_format:'geojson'})});const legs=data.trip?.legs??[];const geometry=legs.flatMap((l:any)=>l.shape?.coordinates??[]).map((x:number[])=>({lon:x[0],lat:x[1]}));const segments=legs.map((l:any)=>l.summary?.length?l.summary.length*1000:0);const returned=data.trip?.locations??[];const order=returned.length===all.length?returned.map((location:any,index:number)=>typeof location.original_index==='number'?all[location.original_index]:all[index]):all;if(!geometry.length)throw Error('Brak geometrii Valhalli');return{order,geometry,segments,totalDistance:segments.reduce((a:number,b:number)=>a+b,0),engine:'Valhalla',generatedAt:Date.now()};}
async function osrm(all:Checkpoint[]):Promise<RouteResult>{const coordinates=all.map(p=>`${p.geo.lon},${p.geo.lat}`).join(';');const data=await request(`${CONFIG.osrm}/route/v1/foot/${coordinates}?overview=full&geometries=geojson&steps=false`);const route=data.routes?.[0];if(!route)throw Error('Brak trasy OSRM');const geometry=(route.geometry?.coordinates??[]).map((x:number[])=>({lon:x[0],lat:x[1]}));const segments=(route.legs??[]).map((l:any)=>l.distance??0);return{order:all,geometry,segments,totalDistance:route.distance??segments.reduce((a:number,b:number)=>a+b,0),engine:'OSRM',generatedAt:Date.now()};}
export async function calculateRoute(base:LatLng,checkpoints:Checkpoint[],first?:Checkpoint,last?:Checkpoint):Promise<RouteResult>{const start=first??checkpoints[0],end=last??checkpoints[checkpoints.length-1];const ordered=start&&end?optimizeOpen(checkpoints,start,end):fallbackOrder(checkpoints,base);const all=[basePoint('base',base),...ordered,basePoint('base-end',base)];try{return await valhalla(all);}catch{try{return await osrm(all);}catch{const segments:number[]=[];for(let i=0;i<all.length-1;i++){await wait(i?1000:0);segments.push(geoDistance(all[i].geo,all[i+1].geo));}return{order:all,geometry:all.map(p=>p.geo),segments,totalDistance:segments.reduce((a,b)=>a+b,0),engine:'geometria',warning:'Valhalla i OSRM są niedostępne. Wynik używa odległości w linii prostej i nie uwzględnia dróg, rzek, jezior ani innych przeszkód.',generatedAt:Date.now()};}}}
