import type { Checkpoint, LatLng, RouteResult } from './types';
import { geoDistance } from './math';
import { optimizeOpen, fallbackOrder } from './optimizer';
export const CONFIG={valhalla:'https://valhalla1.openstreetmap.de',osrm:'https://routing.openstreetmap.de/routed-foot'};
const basePoint=(id:string,geo:LatLng):Checkpoint=>({id,number:'',geo,kind:'base'});
async function request(url:string,init:RequestInit={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),8000);try{const r=await fetch(url,{...init,signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json();}finally{clearTimeout(t);}}
async function valhalla(all:Checkpoint[],optimized=true):Promise<RouteResult>{const endpoint=optimized?'optimized_route':'route';const data=await request(`${CONFIG.valhalla}/${endpoint}`,{method:'POST',headers:{'content-type':'application/json','X-Client-Id':'harpagan-route-planner'},body:JSON.stringify({locations:all.map(p=>({lat:p.geo.lat,lon:p.geo.lon})),costing:'pedestrian',units:'kilometers',shape_format:'geojson'})});const legs=data.trip?.legs??[];const geometry=legs.flatMap((l:any)=>l.shape?.coordinates??[]).map((x:number[])=>({lon:x[0],lat:x[1]}));const segments=legs.map((l:any)=>l.summary?.length?l.summary.length*1000:0);const returned=data.trip?.locations??[];const order=optimized&&returned.length===all.length?returned.map((location:any,index:number)=>typeof location.original_index==='number'?all[location.original_index]:all[index]):all;if(!geometry.length)throw Error('Brak geometrii Valhalli');return{order,geometry,segments,totalDistance:segments.reduce((a:number,b:number)=>a+b,0),engine:'Valhalla',generatedAt:Date.now()};}
async function osrm(all:Checkpoint[]):Promise<RouteResult>{const coordinates=all.map(p=>`${p.geo.lon},${p.geo.lat}`).join(';');const data=await request(`${CONFIG.osrm}/route/v1/foot/${coordinates}?overview=full&geometries=geojson&steps=false`);const route=data.routes?.[0];if(!route)throw Error('Brak trasy OSRM');const geometry=(route.geometry?.coordinates??[]).map((x:number[])=>({lon:x[0],lat:x[1]}));const segments=(route.legs??[]).map((l:any)=>l.distance??0);return{order:all,geometry,segments,totalDistance:route.distance??segments.reduce((a:number,b:number)=>a+b,0),engine:'OSRM',generatedAt:Date.now()};}
export type RouteOptions={includeBaseStart?:boolean;includeBaseEnd?:boolean};
export function buildRoutePoints(base:LatLng|undefined,checkpoints:Checkpoint[],first?:Checkpoint,last?:Checkpoint,options:RouteOptions={}){const start=first??checkpoints[0],end=last??checkpoints[checkpoints.length-1];const reference=base??checkpoints[0]?.geo;const ordered=checkpoints.length===1?[checkpoints[0]]:start&&end?optimizeOpen(checkpoints,start,end):reference?fallbackOrder(checkpoints,reference):[];const all:Checkpoint[]=[];if(base&&options.includeBaseStart!==false)all.push(basePoint('base-start',base));all.push(...ordered);if(base&&options.includeBaseEnd!==false)all.push(basePoint('base-end',base));return all;}
async function withFallback(all:Checkpoint[],optimized:boolean):Promise<RouteResult>{if(all.length<2)throw Error('Trasa wymaga co najmniej dwóch punktów');try{return await valhalla(all,optimized);}catch{try{return await osrm(all);}catch{const segments:number[]=[];for(let i=0;i<all.length-1;i++)segments.push(geoDistance(all[i].geo,all[i+1].geo));return{order:all,geometry:all.map(p=>p.geo),segments,totalDistance:segments.reduce((a,b)=>a+b,0),engine:'geometria',warning:'Valhalla i OSRM są niedostępne. Wynik używa odległości w linii prostej i nie uwzględnia dróg, rzek, jezior ani innych przeszkód.',generatedAt:Date.now()};}}}
export async function calculateRoute(base:LatLng|undefined,checkpoints:Checkpoint[],first?:Checkpoint,last?:Checkpoint,options:RouteOptions={}):Promise<RouteResult>{return withFallback(buildRoutePoints(base,checkpoints,first,last,options),false);}
export async function calculateRouteForOrder(order:Checkpoint[]):Promise<RouteResult>{return withFallback(order,false);}
